// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/msecommerce/user_service/pkg"
	"github.com/msecommerce/user_service/pkg/adapter"
	"github.com/msecommerce/user_service/pkg/config"
	"github.com/msecommerce/user_service/pkg/db"
	"github.com/msecommerce/user_service/pkg/service"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*pkg.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(c)
	if err != nil {
		return nil, err
	}
	userAdapter := adapter.NewUserAdapter(gormDB)
	userService := service.NewUserService(userAdapter)
	serverHTTP := pkg.NewServerHTTP(userService)
	return serverHTTP, nil
}
